### ISSUE TITLE
See value stored in head/tail of queue

### ISSUE THREAD

**Issue by gsegatti** [smol-rs/concurrent-queue#40]
Not sure if this is an anti-pattern towards what you guys have implemented. But I'd like to know if there's any reason as to why there's no functions such as `get_head`, `get_tail` for the `Bounded` and `Unbounded` queues?

I have a use case where I do not want to push an item onto the queue if said item was the last thing to be added. Hence the question.

Thanks!

**Comment by notgull** [comment]
> Not sure if this is an anti-pattern towards what you guys have implemented. But I'd like to know if there's any reason as to why there's no functions such as `get_head`, `get_tail` for the `Bounded` and `Unbounded` queues?

It would be unsound to have these functions with the current implementation of `concurrent-queue`. If `get_tail` returned an `&T`, when a simultaneous pop operation would make it so that reference is invalidated. This would only work if `get_tail` took an `&mut` reference, where the borrow checker can assert that the current user is the only one who has access to the queue.

I would accept a PR adding methods to handle queue operations in an `&mut` way.

> I have a use case where I do not want to push an item onto the queue if said item was the last thing to be added. Hence the question.

It might be worth it to de-duplicate the item at the point where it's popped, i.e. keep a copy of the item on hand and then ignore a `pop()` if it's equal to the last item. If your workload doesn't involve a lot of synchronization, a `Mutex<VecDeque>` would also be an option.

**Comment by gsegatti** [comment]
@notgull I've opened a draft PR #41 so you and the maintainers can give some early feedback!

**Comment by taiki-e** [comment]
Personally, I think something like an iterator that returns a mutable reference to an element is preferable to this. (like [FuturesUnorded::iter_mut](https://github.com/rust-lang/futures-rs/blob/master/futures-util/src/stream/futures_unordered/iter.rs))

**Comment by gsegatti** [comment]
Yep, agree this seems like a bit of an anti-pattern. Will close the PR linked to it.
On another note, something I'd like to see is a circular queue of fixed size. But perhaps this should be another issue.

I'll close this for now and I'll reopen if I ever come around implementing an iterator.
